// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGTyFC7Tkv3qvL4-VlQDMpws2x5TOL36k',
    appId: '1:720669003217:web:538c1f7593eaae1372e4f0',
    messagingSenderId: '720669003217',
    projectId: 'dalel-a82dc',
    authDomain: 'dalel-a82dc.firebaseapp.com',
    storageBucket: 'dalel-a82dc.firebasestorage.app',
    measurementId: 'G-T8THNLG2WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3oet3QKdoHosGuzeZsJAzUCiMlkVyDKQ',
    appId: '1:720669003217:android:8cd4d26cbf167c1c72e4f0',
    messagingSenderId: '720669003217',
    projectId: 'dalel-a82dc',
    storageBucket: 'dalel-a82dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_K_imNkboCpqdwsdm5fmLDZaYgru1e0',
    appId: '1:720669003217:ios:102ef7e6123e45a572e4f0',
    messagingSenderId: '720669003217',
    projectId: 'dalel-a82dc',
    storageBucket: 'dalel-a82dc.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_K_imNkboCpqdwsdm5fmLDZaYgru1e0',
    appId: '1:720669003217:ios:102ef7e6123e45a572e4f0',
    messagingSenderId: '720669003217',
    projectId: 'dalel-a82dc',
    storageBucket: 'dalel-a82dc.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGTyFC7Tkv3qvL4-VlQDMpws2x5TOL36k',
    appId: '1:720669003217:web:a248c956bb06d06072e4f0',
    messagingSenderId: '720669003217',
    projectId: 'dalel-a82dc',
    authDomain: 'dalel-a82dc.firebaseapp.com',
    storageBucket: 'dalel-a82dc.firebasestorage.app',
    measurementId: 'G-GSRELD98KL',
  );
}
